# Generated by Django 3.2.9 on 2021-12-14 18:39

from django.db import migrations, models
import scholarships.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ronin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronin', models.CharField(max_length=46, validators=[scholarships.validators.validate_ronin])),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.CharField(blank=True, max_length=200, null=True)),
                ('lifetime_slp', models.IntegerField(blank=True, null=True)),
                ('built_up_slp', models.IntegerField(blank=True, null=True)),
                ('last_claim', models.DateTimeField(blank=True, null=True)),
                ('total_slp', models.IntegerField(blank=True, null=True)),
                ('in_game_slp', models.IntegerField(blank=True, null=True)),
                ('mmr', models.BigIntegerField(blank=True, null=True)),
                ('daily_average', models.FloatField(blank=True, null=True)),
                ('daily_slp_earned', models.FloatField(blank=True, null=True)),
                ('daily_slp_paid', models.FloatField(blank=True, null=True)),
                ('daily_fiat_earned', models.FloatField(blank=True, null=True)),
                ('daily_fiat_paid', models.FloatField(blank=True, null=True)),
                ('next_claim', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalDailySlp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_daily_slp_earned', models.FloatField(blank=True, null=True)),
                ('total_daily_slp_paid', models.FloatField(blank=True, null=True)),
                ('total_daily_fiat_earned', models.FloatField(blank=True, null=True)),
                ('total_daily_fiat_paid', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
