# Generated by Django 3.2.9 on 2021-12-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaldailyslp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_manager', to='users.manager'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='ronin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarships.ronin'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.scholar'),
        ),
        migrations.AddField(
            model_name='ronin',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
    ]
