# Generated by Django 3.2.9 on 2021-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.CharField(blank=True, max_length=200, null=True)),
                ('ronin', models.CharField(max_length=200)),
                ('ronin_slp', models.IntegerField(blank=True, null=True)),
                ('lifetime_slp', models.IntegerField(blank=True, null=True)),
                ('built_up_slp', models.IntegerField(blank=True, null=True)),
                ('last_claim', models.DateTimeField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('slp_paid', models.IntegerField(blank=True, null=True)),
                ('slp_earned', models.IntegerField(blank=True, null=True)),
                ('fiat_paid', models.IntegerField(blank=True, null=True)),
                ('fiat_earned', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalScholarSlp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slp_earned', models.FloatField(blank=True, null=True)),
                ('total_fiat_earned', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalSlp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slp_earned', models.FloatField(blank=True, null=True)),
                ('total_slp_paid', models.FloatField(blank=True, null=True)),
                ('total_fiat_earned', models.FloatField(blank=True, null=True)),
                ('total_fiat_paid', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
