# Generated by Django 3.2.9 on 2021-12-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_managerteam_temp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerteam',
            name='temp_code',
        ),
    ]
