# Generated by Django 3.2.9 on 2021-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_managerteam_temp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerteam',
            name='temp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
