# Generated by Django 3.2.9 on 2021-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_1', models.IntegerField()),
                ('task_2', models.IntegerField(blank=True, null=True)),
                ('task_3', models.IntegerField(blank=True, null=True)),
                ('task_4', models.IntegerField(blank=True, null=True)),
                ('rate_1', models.IntegerField()),
                ('rate_2', models.IntegerField(blank=True, null=True)),
                ('rate_3', models.IntegerField(blank=True, null=True)),
                ('rate_4', models.IntegerField(blank=True, null=True)),
                ('rate_5', models.IntegerField(blank=True, null=True)),
                ('fixed_rate', models.BooleanField(default=False)),
            ],
        ),
    ]
